apiVersion: apps/v1
kind: Deployment
metadata:
  name: avel
  labels:
    app: avel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: avel
  template:
    metadata:
      name: avel
      labels:
        app: avel
    spec:
      containers:
        - name: avel
          image: alex23451234/avel:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /certs
              name: certs
      restartPolicy: Always
      volumes:
        - name: certs
          secret:
            secretName: cockroach-cockroachdb-ca-secret
            items:
              - key: ca.crt
                path: ca.crt
---

apiVersion: v1
kind: Service
metadata:
  name: avel-service
spec:
  selector:
    app: avel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

