apiVersion: apps/v1
kind: Deployment
metadata:
  name: avel
  labels:
    app: avel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: avel
  template:
    metadata:
      name: avel
      labels:
        app: avel
    spec:
      containers:
        - name: avel
          image: alex23451234/avel:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /certs
              name: certs
            - mountPath: /etc/redis
              name: redis
      restartPolicy: Always
      volumes:
        - name: certs
          secret:
            secretName: cockroach-cockroachdb-ca-secret
            items:
              - key: ca.crt
                path: ca.crt
        - name: redis
          secret:
            secretName: redis

---

apiVersion: v1
kind: Service
metadata:
  name: avel-service
spec:
  selector:
    app: avel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-clear
  labels:
    app: db-clear
spec:
  selector:
    matchLabels:
      app: db-clear

  template:
    metadata:
      name: db-clear
      labels:
        app: db-clear
    spec:
      containers:
        - name: db-clear
          image: alex23451234/avel-clear:latest
          imagePullPolicy: Always

