conf:
  cache: "2Gi"
  max-sql-memory: "4Gi"

  statefulset:
    replicas: 3

tls:
  enabled: true
  certs:
    clientRootSecret: cockroach-root
    nodeSecret: cockroach-node
    caSecret: cockroach-ca

tls.certs.selfSigner.enabled: false
tls.certs.certManager: true
tls.certs.certManagerIssuer.kind: Issuer
tls.certs.certManagerIssuer.name: cockroachdb